#!/usr/bin/env bash
# Copy .env and .env.testing if they don't exists
if [ ! -f .env ]; then
    cp .env.example .env
fi
if [ ! -f .env.testing ]; then
    cp .env.testing.example .env.testing
fi
# Clear config cache
php artisan config:clear
# Clear route cache
php artisan route:clear
# Generate APP_KEY
output=$(php artisan key:generate --force --show)
# Replace or create the APP_KEY environment variable in .env and .env.testing
sed -i "s/^APP_KEY=.*/APP_KEY=${output}/" .env
sed -i "s/^APP_KEY=.*/APP_KEY=${output}/" .env.testing
# Migrate Database
php artisan migrate:fresh
# Run php artisan passport:install command and store the output in a variable
output=$(php artisan passport:install --force)
# Extract Personal Access Client ID and Secret from the output
client_id=$(echo "$output" | awk '/Client ID:/{print $3; exit}')
client_secret=$(echo "$output" | awk '/Client secret:/{print $3; exit}')
# Delete the existing PERSONAL_ACCESS_CLIENT_ID and PERSONAL_ACCESS_CLIENT_SECRET environment variables in .env and .env.testing
sed -i "/^PASSPORT_PERSONAL_ACCESS_CLIENT_ID=/d" .env
sed -i "/^PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=/d" .env
sed -i "/^PASSPORT_PERSONAL_ACCESS_CLIENT_ID=/d" .env.testing
sed -i "/^PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=/d" .env.testing
# Add the new PERSONAL_ACCESS_CLIENT_ID and PERSONAL_ACCESS_CLIENT_SECRET environment variables in .env and .env.testing
echo "PASSPORT_PERSONAL_ACCESS_CLIENT_ID=${client_id}" >> .env
echo "PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=${client_secret}" >> .env
echo "PASSPORT_PERSONAL_ACCESS_CLIENT_ID=${client_id}" >> .env.testing
echo "PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=${client_secret}" >> .env.testing
# Cache Config
php artisan config:cache
# Cache Routes
php artisan route:cache
# Seed Database
php artisan db:seed
# Install Telescope module
php artisan telescope:install
php artisan telescope:publish
# Link storage
php artisan storage:link
# Install scribe
php artisan scribe:generate --force
# Start Supervisor Service
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
