#!/usr/bin/env bash
# run composer install if it vendor does not exists.
if [ ! -d "vendor" ]; then
    composer install
fi

if [[ -z "${ARTISAN_MIGRATE}" ]]; then
    php artisan migrate
fi

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    if [[ -z "${ARTISAN_SERVE}" ]]; then
        php artisan serve --host 0.0.0.0 --port 8000
    fi
fi
