#!/usr/bin/env bash

whoami

composer install
npm install

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

FILE=setup.sh
if test -f "$FILE"; then
    echo "Running setup"
    ./setup
fi

service cron start
service supervisor start